---
title: "README"
author: "jsg"
date: "8/21/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting started

At this point I’m assuming you received the invitation to view the assignment on
github classroom and accepted it. You now have a private repository of these files. 
To start working on the assignment, open RStudio (on your desktop or cloudserver). 
Select file, new project, Version control. On the next screen select git. Next 
you’ll need to enter the url for your repository. Navigate to the web home of 
your github repository and for the green Code button. Click it, then copy the 
web url (or click the copy icon). Input that into the Rstudio Repository URL 
space. Then name the project (maybe Assignment 1,2, etc?). The Create project… 
field can be left blank to just save all projects into the main directory.
Alternatively you can click Browse and make an Assignments folder if you want.
Whatever you choose, the project will be saved in new folder in that location 
using the name you chose.

Now you can start working on the assignment in Rstudio.  To view instructions, 
click on the .md file associated with the assignment you want ON GITHUB (IN YOUR '
BROWSER!) OR SELECT KNIT THE FILE (IN RSTUDIO!).