---
title: "3. Introduction to hypothesis testing via binomial tests"
author: "jsg"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y %H:%M')`"
output:
  html_document:
    toc: true
    toc_float: true
    keep_md: true
    self_contained: true
---

Before doing this, review the **Introduction To Hypothesis Testing Via Binomial Tests** lecture set slides from 
https://sites.google.com/view/biostats/lessons/hypothesis-testing-with-the-binomial-distribution and
the  **3_hypothesis_testing_and_binomial.R** script in the lecture_files folder of the
[CUNY-BioStats github repository](https://github.com/jsgosnell/CUNY-BioStats).  
You should also complete the swirl tutorial first!


Remember you should

* add code chunks by clicking the *Insert Chunk* button on the toolbar or by
pressing *Ctrl+Alt+I* to answer the questions!
* **knit** your file to produce a markdown version that you can see!
* save your work often 
  * **commit** it via git!
  * **push** updates to github

## Hypothesis Testing and the Binomial Distribution

Make sure you are comfortable with null and alternative hypotheses for all examples.

1. Are people eared (do they prefer one ear or another)?  Of 25 people observed 
while in conversation in a nightclub, 19 turned their right ear to the speaker 
and 6 turn their left ear to the speaker.  How strong is the evidence for 
eared-ness given this data (adapted from Analysis of Biological Data)?
* state a null and alternative hypothesis
* calculate a test statistic (signal) for this data
* Make you understand how to construct a null distribution
  + using sampling/simulation (code or written explanation)
  + by using an appropriate distribution (code or written explanation)
*Calculate and compare p-values obtained using 
  + simulation (calculation won’t be required on test, but make sure you understand!) (code or written explanation)
  + equations for binomial distribution (code or written explanation) 
  + R functions (required)(code)
* Calculate a 95% confidence interval for the proportion of people who are right-eared
* How do your 95% confidence interval and hypothesis test compare?

2.  A professor lets his dog take every multiple-choice test to see how it 
compares to his students (I know someone who did this).  Unfortunately, the
professor believes undergraduates in the class tricked him by helping the dog 
do better on a test. It’s a 100 question test, and every questions has 4 answer 
choices.  For the last test, the dog picked 33 questions correctly.  How likely
is this to happen, and is there evidence the students helped the dog?	

**MAKE SURE TO THINK ABOUT YOUR TEST OPTIONS**
